---

- hosts: samba
  remote_user: deploy
  become: "yes"
  become_user: "root"
  become_method: "sudo"

  vars:
    servername: "{{ inventory_hostname }}"
    docker_users:
      - deploy
      - goto

  roles:
    - { role: info, tags: ['info'] }
    - { role: common, tags: ['common'] }
    - { role: docker, tags: ['docker'] }
    - { role: docker-compose, tags: ['docker-compose'] }
    - { role: veeam, tags: ['veeam'] }
    - { role: ufw, tags: ['ufw'] }
    - { role: samba, tags: ['samba'] }
