---

- name: "Install samba package"
  apt:
    name: samba

- name: "Push samba config"
  template:
    src: "roles/samba/templates/smb.conf.j2"
    dest: "/etc/samba/smb.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: "Reboot samba that smb.conf changes to apply"

- name: "Ensure Windows limit (16384)"
  lineinfile:
    path: "/etc/security/limits.conf"
    regexp: "-       nofile          16384$"
    insertbefore: "^# End of file"
    line: "*                -       nofile          16384"
  notify: "Reboot a machine that file changes to apply (/etc/security/limits.conf)"

- name: "Create groups"
  group:
    name: "{{ item.1 }}"
    state: present
  loop: "{{ group_dict | dict2items | subelements('value.name') | list }}"

- name: "Create folders"
  file:
    path: "{{ path_to_mount_raid }}/{{ item.1 }}"
    owner: root
    group: "{{ item.1 }}"
    mode: u=rwx,g=rwxs,o-rwx
    state: directory
  loop: "{{ group_dict | dict2items | subelements('value.name') | list }}"

- name: "Create users"
  user:
    name: "{{ item.key }}"
    comment: "{{ item.value.description }}"
    password: "{{ item.value.password }}"
    shell: /usr/sbin/nologin
    groups: "{{ item.value.grps | list }}"
    home: "{{ path_to_mount_raid }}/users_private/{{ item.key }}"
    expires: 1422403387
  loop: "{{ lookup('dict', users) }}"

- name: "Sets default ACL"
  acl:
    path: "{{ path_to_mount_raid }}/{{ item.1 }}"
    entity: olegs_folder
    etype: group
    permissions: rw
    default: yes
    state: present
  loop: "{{ group_dict | dict2items | subelements('value.name') | list }}"

#- name: "Set a password and enable users"
#  shell: "(echo {{ item.value.password }} | smbpasswd -s -a {{ item.key }}"
#  loop: "{{ lookup('dict', users) }}"
