---

- name: "Install samba package"
  apt:
    name: samba

- name: "Push samba config"
  template:
    src: "roles/samba/templates/smb.conf.j2"
    dest: "/etc/samba/smb.conf"
    owner: root
    group: root
    mode: 0600
  notify: "Reboot samba that smb.conf changes to apply"

- name: "Ensure Windows limit (16384)"
  lineinfile:
    path: "/etc/security/limits.conf"
    regexp: "-       nofile          16384$"
    insertbefore: "^# End of file"
    line: "*                -       nofile          16384"
  notify: "Reboot a machine that file changes to apply (/etc/security/limits.conf)"

- name: "Create groups"
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ group_list }}"

- name: "Create folders"
  file:
    path: "/raid/{{ item }}"
    owner: root
    group: "{{ item }}"
    mode: u=rwx,g=rwxs,o-rwx
    mode: u=rwx,g=rwxs,o-rwx
    state: directory
  loop: "{{ group_list }}"

- name: "Create users"
  user:
    name: "{{ item.key }}"
    shell: /bin/bash
    password: "{{ item.value.password }}"
    # shell: /usr/sbin/nologin
    groups: "{{ item.value.grps|list }}"
    home: "/raid/users_private/{{ item.key }}"
    expires: 1422403387
  loop: "{{ lookup('dict', users) }}"

#- name: "Set a password and enable users"
#  shell: "(echo {{ item.value.password }} | smbpasswd -s -a {{ item.key }}"
#  loop: "{{ lookup('dict', users) }}"
