---
path_to_mount_raid: /raid

group_dict:
  private_user_folders:
    name:
      - users_private
  public_user_folders:
    name:
      - shared
      - UpdateWinCAD5
  special_user_folders:
    name:
      - accountants_folder
      - olegs_folder

users:
  user1:
    description: "User firstname and surname"
    password: "{{ '111' | password_hash('sha512', 'Desalt8') }}"
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
  user2:
    description: "User firstname and surname"
    password: "{{ '222' | password_hash('sha512', 'Desalt8') }}"
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
  user3:
    description: "User firstname and surname"
    password: "{{ '333' | password_hash('sha512', 'Desalt8') }}"
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
      - accountants_folder
  user4:
    description: "User firstname and surname"
    password: "{{ '444' | password_hash('sha512', 'Desalt8') }}"
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
      - olegs_folder
  user5:
    description: "User firstname and surname"
    password: "{{ '555' | password_hash('sha512', 'Desalt8') }}"
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
      - olegs_folder
