---
path_to_mount_raid: /raid

group_dict:
  private_user_folders:
    name:
      - users_private
  public_user_folders:
    name:
      - shared
      - UpdateWinCAD5
  special_user_folders:
    name:
      - accountants_folder
      - oleg_folder

users:
  user1:
    description: "User firstname and surname"
    smbpassword: "ieGhei4a"
    state: present
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
  user2:
    description: "User firstname and surname"
    smbpassword: "johPh5oo"
    state: present
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
  user3:
    description: "User firstname and surname"
    smbpassword: "tahdie5O"
    state: present
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
      - accountants_folder
  user4:
    description: "User firstname and surname"
    smbpassword: "im1TiThe"
    state: present
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
      - oleg_folder
  user5:
    description: "User firstname and surname"
    smbpassword: "ahSah6fo"
    state: present
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
      - oleg_folder
