---
group_list:
  - users_private
  - shared
  - UpdateWinCAD5
  - accountants_folder
  - olegs_folder

users:
  user1:
    password: "{{ 'Dfkwekl' | password_hash('sha512', 'd32r44') }}"
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
  user2:
    password: "{{ 'mypassword' | password_hash('sha512', 'mysecretsalt') }}"
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
  user3:
    password: "{{ 'mypassword' | password_hash('sha512', 'mysecretsalt') }}"
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
      - accountants_folder
  user4:
    password: "{{ 'mypassword' | password_hash('sha512', 'mysecretsalt') }}"
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
      - olegs_folder
