---
path_to_mount_raid: /raid

group_dict:
  private_user_folders:
    settings:
      - name: users_private
        params:
          mode: "u=rwxs,g=rwxs,o-rwx"
          owner: nobody
          folder_state: directory
          grp_state: present
          acl_state: present
  public_user_folders:
    settings:
      - name: shared
        params:
          mode: "u=rwxs,g=rwxs,o-rwx"
          owner: nobody
          folder_state: directory
          grp_state: present
          acl_state: present
      - name: UpdateWinCAD5
        params:
          mode: "u=rwxs,g=rwxs,o-rwx"
          owner: nobody
          folder_state: directory
          grp_state: present
          acl_state: present
  special_user_folders:
    settings:
      - name: accountants_folder
        params:
          mode: "u=rwxs,g=rwxs,o-rwx"
          owner: nobody
          folder_state: directory
          grp_state: present
          acl_state: present
      - name: oleg_folder
        params:
          mode: "u=rwxs,g=rwxs,o-rwx"
          owner: nobody
          folder_state: directory
          grp_state: present
          acl_state: present
      - name: local-http-server
        params:
          mode: "u=rwxs,g-rwx,o=rx"
          owner: nobody
          folder_state: directory
          grp_state: present
          acl_state: present
      - name: .deleted
        params:
          mode: "u=rwxs,g=rwxs,o-rwx"
          owner: nobody
          folder_state: absent
          grp_state: absent
          acl_state: absent

users:
  user1:
    description: "User firstname and surname"
    smbpassword: "ieGhei4a"
    state: present
    enabled: "yes"
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
  user2:
    description: "User firstname and surname"
    smbpassword: "johPh5oo"
    state: present
    enabled: "yes"
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
  user3:
    description: "User firstname and surname"
    smbpassword: "tahdie5O"
    state: present
    enabled: "yes"
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
      - accountants_folder
  user4:
    description: "User firstname and surname"
    smbpassword: "im1TiThe"
    state: present
    enabled: "yes"
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
      - oleg_folder
  user5:
    description: "User firstname and surname"
    smbpassword: "ahSah6fo"
    state: present
    enabled: "yes"
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
      - oleg_folder
  user6:
    description: "User firstname and surname"
    smbpassword: "esh8Eem1"
    state: absent
    enabled: "no"
    grps:
      - users_private
      - shared
      - UpdateWinCAD5
      - oleg_folder
