---

- name: "Update cache"
  apt:
    update_cache: "{{ update_cache }}"
    cache_valid_time: "{{ cache_valid_time }}"

- name: "Install software"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - curl
    - wget
    - tmux
    - glances
    - atop
    - ncdu
    - iotop
    - net-tools
    - git
- name: Set timezone to your timezone
  timezone:
    name: "{{ timezone }}"
